[feat] 일기장 생성 기능 추가
minmk01/record pull request #1
Opened 2024-09-15 04:07 UTC by minmk01

2024-09-28 01:40 UTC, iooooon requested changes

2024-09-28 01:40 UTC, iooooon commented on src/main/java/com/example/record/RecordController.java
> +    public Optional<Record> readRecord(@PathVariable int id) {
Integer 가 아닌 int를 사용하신 이유가 있을까요? 특별한 이유가 없다면 Wrapper Class 를 사용하는 것이 좋습니다.

2024-09-28 01:40 UTC, iooooon commented on src/main/java/com/example/record/RecordService.java
> +    public Optional<Record> readRecord(int id) {
조회 메서드의 네이밍 컨벤션은 read 보다는 get 을 사용하는 것이 훨씬 일반적입니다.

2024-09-28 01:40 UTC, iooooon commented on src/main/java/com/example/record/RecordService.java
> +
작성 중인 코드를 올리실 때 주석이나 에러가 발생하는 코드는 존재해도 괜찮지만 코드 포맷팅은 되어 있어야 합니다.

2024-09-28 01:40 UTC, iooooon commented on src/main/resources/application.yml
> +#spring:
아래 주석은 내용상 위 설정값들과 동일한 역할을 하는 것으로 보이는데 남겨놓은 이유가 있을까요?

2024-09-28 01:40 UTC, iooooon commented on src/main/java/com/example/record/RecordRepository.java
> +public interface RecordRepository extends JpaRepository<Record, Integer> {
Entity 의 Primary Key 의 타입을 Integer 로 사용한 이유가 있을까요?

2024-09-28 01:40 UTC, iooooon commented on src/main/java/com/example/record/User.java
> +    private int id;
여기는 Primary Key 타입이 int 로 되어 있는데 Long 으로 통일이 필요할 것 같습니다.

2024-09-28 01:40 UTC, iooooon commented on src/main/java/com/example/record/User.java
> +    private int id;
@GeneratedValue 어노테이션의 전략 타입 설정이 필요할 것 같습니다. @Column 어노테이션은 어떤 이유로 추가하셨을까요?

2024-09-29 09:44 UTC, minmk01 commented on src/main/resources/application.yml
> +#spring:
주석 처리된 부분은 위 설정값을 수정하기 전 기존 설정값인데 수정 당시, 제가 application 파일에 대해 아는 것이 많이 부족하니 뭐라도 하나 더 알아 두면 도움이 될까 하는 마음에 차이가 나는 부분을 남겨두고 싶어 주석 처리를 해놓았었습니다. 지금은 다른 곳으로 코드를 옮겨 놓아 삭제하였습니다.

2024-10-02 12:41 UTC, minmk01 commented on src/main/java/com/example/record/User.java
> +    private int id;
PK 에도 @Column(name = “”) 을 사용하는 코드를 보고 저도 사용을 해보려고 어떻게 해야 할지 고민하다가 작성했던 name 부분만 지우고 @Column 어노테이션은 그대로 남겨둔 채로 잊어버렸습니다. 확실히 정리하고 넘어가지 않은 제 실수 입니다.

2024-10-02 12:41 UTC, minmk01 commented on src/main/java/com/example/record/User.java
> +    private int id;
이온님의 피드백을 통해 구글링을 해본 결과, Primary Key 는 @Id 어노테이션으로 나타내고 @GeneratedValue 어노테이션으로 전략 타입을 설정한다는 것을 알게 되어 제가 사용 중인 DB인 H2 에 해당하는 전략 타입인 strategy=GenerationType.SEQUENCE 을 추가해주었습니다.

2024-10-03 05:31 UTC, iooooon requested changes

2024-10-03 05:31 UTC, iooooon commented on src/main/java/com/example/record/BaseEntity.java
> +@NoArgsConstructor
Entity 에 @NoArgsConstructor 을 사용할 때 아래 링크의 내용도 함께 알고 사용하면 더 좋을 것 같습니다!
https://velog.io/@kevin_/%EB%82%B4%EA%B0%80-NoargsConstructor-access-AccessLevel.PROTECTED%EB%A5%BC-%EC%99%9C-%EC%9E%91%EC%84%B1%ED%96%88%EC%9D%84%EA%B9%8C

2024-10-03 05:31 UTC, iooooon commented on src/main/java/com/example/record/BaseEntity.java
> +public abstract class BaseEntity {
BaseEntity 는 많이 사용하는 클래스 중 하나인데 적용을 너무 잘 하신 것 같습니다 :)
id 필드도 공통으로 사용되는 부분이니 추가해보시는건 어떨까요?

2024-10-03 05:31 UTC, iooooon commented on src/main/java/com/example/record/Comment.java
> +@SuperBuilder
BaseEntity 에도 SuperBuilder 가 있던데 상속을 받는 클래스에도 SuperBuilder 어노테이션을 붙여야 생각하신대로 작동하는걸까요? 저도 이 부분은 잘 몰라서 여쭤봅니다!

2024-10-03 05:36 UTC, iooooon commented on src/main/java/com/example/record/User.java
> +    private int id;
이런 글들도 같이 참고해보시면 좋을 것 같습니다! SEQUENCE 가 실제로 어떤 동작을 하는 전략인지도 같이 공부해보시면 좋을 것 같아요 :)
https://github.com/HomoEfficio/dev-tips/blob/master/JPA-GenerationType-%EB%B3%84-INSERT-%EC%84%B1%EB%8A%A5-%EB%B9%84%EA%B5%90.md
https://lordofkangs.tistory.com/358

위 블로그 글들은 정석적인 글은 아니니 참고만 부탁드립니다!

2024-10-03 06:44 UTC, minmk01 commented on src/main/java/com/example/record/Comment.java
> +@SuperBuilder
SuperBuilder 어노테이션을 사용하려면 부모 클래스와 자식 클래스 모두에게 붙여 주어야 한다는 글을 보고 넣어주었습니다!

2024-10-07 08:50 UTC, minmk01 commented on src/main/java/com/example/record/Record.java
> +    private Long authorId;
name 속성을 굳이 사용하지 않아도 된다고 하셨는데 @JoinColumn 어노테이션에 있는 name 을 말씀하시는 게 맞는 걸까요? 일단은 그렇게 이해하고 삭제하던 중, User 엔티티 클래스에는 유저 id 를 의미하는 id (Primary key) 가 있고 Record 엔티티 클래스에는 작성한 일기 id 를 의미하는 id (Primary key) 와 일기를 작성한 유저를 의미하는 authorId 가 있는데 authorId 에는 일기를 작성한 유저에 대한 정보가 어떻게 담기게 되나요..?

2024-10-07 09:26 UTC, minmk01 commented on src/main/java/com/example/record/BaseEntity.java
> +    private LocalDateTime createdDate;
@Column 어노테이션으로 정의한 updatable 속성 부분도 SQL 로 직접 설정해 줄 수 있는 건가요?

2024-10-08 08:10 UTC, minmk01 commented on src/main/java/com/example/record/Record.java
> +    private Long authorId;
Table [comment] contains physical column name [record_id] referred to by multiple logical column names: [record_id], [recordId]
위 에러 메시지를 통해 구글링을 해본 결과, 외래키는 Entity에 추가하지 않아도 되고 @JoinColumn 을 통해 자동 생성 되기 때문에 중복된 컬럼에 대한 에러가 떴다는 것을 알게 되어 외래키라 생각하며 추가했던 컬럼들은 모두 삭제하였습니다. @JoinColumn 과 관련하여 구글링을 해봤지만 이해가 되는 듯 싶다가도 다시 헷갈리는 느낌을 받아 왔는데 조금은 정리가 된 듯 싶습니다.

2024-10-08 08:14 UTC, minmk01 commented on src/main/java/com/example/record/Record.java
> +    private Long authorId;
Record 엔티티 클래스에 대한 에러라서 이 곳에 이어서 남깁니다.
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "\000d\000a    create table record (\000d\000a        cheer_up integer,\000d\000a        is_shared boolean,\000d\000a        [*]like integer,\000d\000a        created_date timestamp(6),\000d\000a        id bigint not null,\000d\000a        updated_date timestamp(6),\000d\000a        user_id bigint,\000d\000a        comments varchar(255),\000d\000a        contents varchar(255),\000d\000a        feeling varchar(255),\000d\000a        one_sentence varchar(255),\000d\000a        primary key (id)\000d\000a    )"; expected "identifier"; SQL statement:

H2 Database 에서 확인해보니 Record 테이블만 없고 나머지 User, Comment, selfInterview 테이블은 추가되어 있었습니다.

2024-10-08 08:37 UTC, minmk01 commented on src/main/java/com/example/record/Record.java
> +    private Long authorId;
예약어 에러인 걸까요..?

2024-10-08 08:59 UTC, minmk01 commented on src/main/java/com/example/record/Record.java
> +    private Long authorId;
https://stackoverflow.com/questions/66333101/how-to-fix-org-h2-jdbc-jdbcsqlsyntaxerrorexception-syntax-error-in-sql-statemen
여기에는 예약어 에러이고 Hibernate ORM guide 문서에서 백틱을 사용해주면 해결 가능하다고 안내하고 있다는 답변이 달려 있는 것 같은데  어떻게 해야 할까요..

2024-10-08 15:34 UTC, iooooon requested changes

2024-10-08 15:34 UTC, iooooon commented on src/main/java/com/example/record/Record.java
> +    private Long authorId;
제가 말한 name 은 @Table 어노테이션 안에 있는 name 속성을 의미한 내용이었습니다! @Table 어노테이션을 생략해도 된다는 의미에서 말씀드렸고, 기본적으로 엔티티 이름을 @Table(name="record") 와 같이 명시하지 않으면 해당 클래스의 이름을 소문자로 하여 자동으로 테이블이 생성됩니다.

2024-10-08 15:34 UTC, iooooon commented on src/main/java/com/example/record/Record.java
> +    private Long authorId;
에러의 경우 H2 Console 에서 모든 테이블을 삭제하고 서버를 재시작 해보시고, 그래도 에러가 발생한다면 모든 엔티티에 @Table(name=records) 이런식으로 s를 붙인 이름을 달아주신 후 재시작해보시길 바랍니다.

2024-10-08 17:05 UTC, minmk01 commented on src/main/java/com/example/record/Record.java
> +    private Long authorId;
알려주신 방법대로 모두 해보아도 해결이 안되어 방법을 찾아보던 중, 예약어 목록을 찾게 되어 봐보니 like 가 있길래 Record 엔티티에 있던 like 컬럼을 likes 로 바꾸었더니 해결되었습니다.

2024-10-09 08:47 UTC, iooooon commented
LGTM!!

2024-10-09 09:31 UTC, merged